version: "3.9"
services:
  py3:
    build:
      context: .
      dockerfile: Dockerfile

    entrypoint: >
      jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/workspace
    #--NotebookApp.token='' Notebook アクセス時の token 文字列を設定できる

    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_setting:/root/.jupyter
      - ./workspace:/workspace
    # GPUを使う場合の設定
    # environment:
    #   - "NVIDIA_VISIBLE_DEVICES=all"
    #   - "NVIDIA_DRIVER_CAPABILITIES=all"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
